package util;

import action.TotalCount;
import action.course.AddLectionToCourse;
import action.course.AddLectorToCourse;
import action.course.AddStudentToCourse;
import action.course.CreateCourse;
import action.course.DeleteCourse;
import action.course.DeleteLectionFromCourse;
import action.course.DeleteLectorFromCourse;
import action.course.DeleteStudentFromCourse;
import action.lection.AddCourseToLection;
import action.lection.CreateLection;
import action.lection.DeleteCourseFromLection;
import action.lection.DeleteLection;
import action.lector.AddCourseToLector;
import action.lector.CreateLector;
import action.lector.DeleteCourseFromLector;
import action.lector.DeleteLector;
import action.student.CreateStudent;
import action.student.DeleteStudent;
import menu.Menu;
import menu.MenuPoint;

public class MenuBuilder {
	public static Menu buildMenu() {
		Menu mainMenu = new Menu("Main menu");
		Menu bd = new Menu("work with database");
		Menu show = new Menu("show information");
		mainMenu.Add(new MenuPoint(bd, "Work with database"));
		mainMenu.Add(new MenuPoint(show, "Show Information"));
		mainMenu.Add(new MenuPoint(null, "exit"));
		Menu courseServ = new Menu("Course menu");
		courseServ.Add(new MenuPoint(bd, "create course", new CreateCourse()));
		courseServ.Add(new MenuPoint(bd, "delete course", new DeleteCourse()));
		courseServ.Add(new MenuPoint(bd, "add lector to course", new AddLectorToCourse()));
		courseServ.Add(new MenuPoint(bd, "delete lector from course", new DeleteLectorFromCourse()));
		courseServ.Add(new MenuPoint(bd, "add lection to course", new AddLectionToCourse()));
		courseServ.Add(new MenuPoint(bd, "delete lection from course", new DeleteLectionFromCourse()));
		courseServ.Add(new MenuPoint(bd, "add student to course", new AddStudentToCourse()));
		courseServ.Add(new MenuPoint(bd, "delete student from course", new DeleteStudentFromCourse()));
		Menu lectorServ = new Menu("Lector menu");
		lectorServ.Add(new MenuPoint(bd, "create lector", new CreateLector()));
		lectorServ.Add(new MenuPoint(bd, "delete lector", new DeleteLector()));
		lectorServ.Add(new MenuPoint(bd, "add course to lector", new AddCourseToLector()));
		lectorServ.Add(new MenuPoint(bd, "delete course from lector", new DeleteCourseFromLector()));
		Menu lectionServ = new Menu("Lection Menu");
		lectionServ.Add(new MenuPoint(bd, "create lection", new CreateLection()));
		lectionServ.Add(new MenuPoint(bd, "delete lection", new DeleteLection()));
		lectionServ.Add(new MenuPoint(bd, "add course to lection", new AddCourseToLection()));
		lectionServ.Add(new MenuPoint(bd, "delete course from lection", new DeleteCourseFromLection()));
		lectionServ.Add(new MenuPoint(bd, "add data for lection", null));
		lectionServ.Add(new MenuPoint(bd, "delete data from lection", null));
		Menu studentServ = new Menu("Student menu");
		lectionServ.Add(new MenuPoint(bd, "sozdat stydenta", new CreateStudent()));
		lectionServ.Add(new MenuPoint(bd, "ydalit stydenta", new DeleteStudent()));
		lectionServ.Add(new MenuPoint(bd, "dobavit kyrs y stydenta", null));
		lectionServ.Add(new MenuPoint(bd, "ydalit kyrs y stydenta", null));
		bd.Add(new MenuPoint(courseServ, "ypravlenie kyrsami"));
		bd.Add(new MenuPoint(lectorServ, "ypravlenie lektorami"));
		bd.Add(new MenuPoint(lectionServ, "ypravlenie lekciyami"));
		bd.Add(new MenuPoint(studentServ, "ypravlenie studentami"));
		bd.Add(new MenuPoint(mainMenu, "na glavnoe menu"));
		Menu courseInfo = new Menu("informaciya o kyrse");
		courseInfo.Add(new MenuPoint(mainMenu,"sortirovat po date nachala",null));
		courseInfo.Add(new MenuPoint(mainMenu,"sortirovat po kolichestvy stydentov",null));
		courseInfo.Add(new MenuPoint(mainMenu,"sortirovat po lektory",null));
		courseInfo.Add(new MenuPoint(mainMenu,"sortirovat po alfavity",null));
		courseInfo.Add(new MenuPoint(mainMenu,"spisok kyrsov posle dati",null));
		courseInfo.Add(new MenuPoint(mainMenu,"spisok kyrsov kotorie yje idyt",null));
		Menu lectorInfo = new Menu("informaciya o lektorah");
		lectorInfo.Add(new MenuPoint(mainMenu,"sortirovat po alfavity",null));
		lectorInfo.Add(new MenuPoint(mainMenu,"sortirovat po kolichestvy kyrsov",null));
		Menu lectionInfo = new Menu("informaciya o lekciyah");
		lectionInfo.Add(new MenuPoint(mainMenu,"sortirovat po alfavity",null));
		lectionInfo.Add(new MenuPoint(mainMenu,"sortirovat po date",null));
		lectionInfo.Add(new MenuPoint(mainMenu,"spisok lekcii na daty",null));
		show.Add(new MenuPoint(courseInfo, "pokazat infy o kyrse"));
		show.Add(new MenuPoint(lectorInfo, "pokazat infy o lektorah"));
		show.Add(new MenuPoint(lectionInfo, "pokazat infy o lekciyah"));
		show.Add(new MenuPoint(mainMenu, "total count of courses, lectors, lections, students", new TotalCount()));
		show.Add(new MenuPoint(mainMenu, "na glavnoe menu"));
		return mainMenu;
	}

}
